### ISSUE TITLE
can't get coverart-browser to work

### ISSUE THREAD

**Issue by tnuk** [fossfreedom/coverart-browser#388] opened 2016-09-07 16:35 UTC
Hi, I am using ubuntu 16.04, installed from scratch. had to re-install rhythmbox 3.4 and now I can't get the coverart-browser to run, no matter how I followed instructions.. when I go on rhythmbox/tools/plugins the coverart-browser shows as one of the plugins when I want to click it to activate it it shows me the red no-entry icon.

PLEASE HELP, I am lost without that function. let me know if you need any other info

thanks, Tony

**Comment by fossfreedom** [comment] 2016-09-07 18:50
Sorry - this is a duplicate of this https://github.com/fossfreedom/coverart-browser/issues/387

**Closed by fossfreedom** 2016-09-07 18:50 UTC

**Comment by tnuk** [comment] 2016-11-27 14:07
Hello David,

tried everything for quite a while now to get the coverart browser going
and I'm quite in despair. love rhythmbox and the the coverart-browser too
much to move to a different player. PLEASE take some time and help me out.
if thats ok what would be my first step? maybe delete rhythmbox and start
anew? thanks.. sorry to bother

Regards, Tony
