### ISSUE TITLE
Conflict found with another plugin on Ubuntu 16.04

### ISSUE THREAD

**Issue by seanthewebber** [fossfreedom/coverart-browser#386] opened 2016-05-14 14:23 UTC
After installing `rhythmbox-plugin-coverart-browser` from the PPA on Ubuntu 16.04, Rhythmbox 3.3 fails to enable the plugin. I am a newbie to Rhythmbox, but there seems to be some sort of conflict with another plugin:

![rhythmbox-configure-plugins](https://cloud.githubusercontent.com/assets/9794367/15268932/38d7f176-19bd-11e6-940a-560bf9dbcb9c.png)

![rhythmbox-plugins-conflict](https://cloud.githubusercontent.com/assets/9794367/15268935/47dcf7ca-19bd-11e6-9bc8-65333fa7444c.png)

Is this issue caused by another plugin I have installed, or is Coverart Browser not compatible with Ubuntu 16.04 yet?

**Comment by fossfreedom** [comment] 2016-05-14 16:46
I'm afraid its not compatible with 16.04 as yet - GNOME guys broke stuff again - I'll need to find some time to catch up.

**Comment by seanthewebber** [comment] 2016-05-15 15:35
@fossfreedom Yeah, that is understandable. I do not know how to program Python or JavaScript, but if there is anything else I can do to help (provide logs, pen test, etc.), please let me know.

**Comment by electricworry** [comment] 2016-06-02 21:35
Anything I can do to help?

**Comment by fossfreedom** [comment] 2016-06-02 22:45
latest code is on gtk318 branch.  This branch stops various crashes.  However the main coverart display is broken - that needs debugging and fixing.

**Comment by fossfreedom** [comment] 2016-09-07 18:50
duplicate of this https://github.com/fossfreedom/coverart-browser/issues/387

**Closed by fossfreedom** 2016-09-07 18:50 UTC
