### ISSUE TITLE
Can't launch after enabling coverart-browser plugin

### ISSUE THREAD

**Issue by AceThaGemini** [fossfreedom/coverart-browser#391] opened 2016-11-09 12:25 UTC
The player doesn't start at all.. :(

## Terminal Output

(rhythmbox:2679): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(rhythmbox:2679): Gtk-CRITICAL **: `gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL'` failed
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_widgets.py:26: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_covericonview.py:28: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/usr/lib/rhythmbox/plugins/coverart_browser/coverart_artistinfo.py:65: PyGIWarning: WebKit was imported without specifying a version first. Use gi.require_version('WebKit', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit
/usr/lib/rhythmbox/plugins/equalizer/Conf.py:20: PyGIWarning: GConf was imported without specifying a version first. Use gi.require_version('GConf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GConf, Gst

(rhythmbox:2679): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:2679): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:2679): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:2679): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:2679): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

(rhythmbox:2679): Gtk-WARNING **: Duplicate child name in GtkStack: Add to Playlist

Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 233, in elapsed_changed
    `if self._scenario != 4:`
AttributeError: 'RememberTheRhythm' object has no attribute '_scenario'
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 168, in playing_source_changed
    `if self._scenario != 4:`
AttributeError: 'RememberTheRhythm' object has no attribute '_scenario'

(rhythmbox:2679): Gtk-CRITICAL **: `gtk_box_reorder_child:` assertion `'old_link != NULL'` failed
Segmentation fault

**Comment by fossfreedom** [comment] 2016-11-09 13:18
duplicate of this https://github.com/fossfreedom/coverart-browser/issues/387

Sorry about that.  Still looking for someone to help fix these issues.

**Closed by fossfreedom** 2016-11-09 13:18 UTC
